service: cart-service
frameworkVersion: '3'
useDotenv: true

plugins:
#   - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1 

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '/{proxy+}'
          cors: true